### ISSUE TITLE
setup.py uses deprecated os.path.walk

### ISSUE THREAD

**Issue by code-of-kpp** [fpom/snakes#11]
os.path.walk function is deprecated and is removed from Python3

The library seems to work with python3 but installation fails since 0.9.21 because of this.

Fun thing is that setup.py currently uses both supported os.walk and deprecated os.path.walk

**Comment by fpom** [comment]
Fixed in a96c6718285f758ac5e8a4268e509e08c767fee1
Thanks for reporting!
