### ISSUE TITLE
time petri nets question

### ISSUE THREAD

**Issue by AarBee1** [fpom/snakes#17]
I have been using tpn.py to model and perform scheduling for a cluster of interconnected industrial equipment where each piece of equipment is designated as a place and the movement between places as well as processing at each place is represented by transitions. 

A type of constraint that I am unable to model is that a token has a time limit on how long it can stay at a place. This (as far as I have been able to figure out) cannot be mapped into the Time Petri Net formalism as the timing is imposed only on transitions that are enabled.

Are there any suggestions as to how this constraint can be mapped into the Time Petri Net formalism? If that is not possible, any recommendations on how such timing constraints can be implemented.

**Comment by fpom** [comment]
Tokens can be any Python objects, so I'd suggest that you use a custom class that holds together a timings and the token value. In its simplest form, it could be pairs (time,token). Then, either you create a Petri net that explicitly takes care of these timing information, or you subclass Place and Transition classes to do it automatically (in particular, I'm thinking about Place.add to initialize timings, and Transition.modes / Transition.fire to check timings). Then, you'll also need to find a way to let time pass, I'd suggest a method on PetriNet that increment every token's time with the same amount in such a way that no time limit is violated. I do something similar to model time Petri nets here : https://snakes.ibisc.univ-evry.fr/articles/time-petri-nets-with-snakes.html

**Comment by AarBee1** [comment]
Thank you. I will give this a go.
