### ISSUE TITLE
snakes.plugins.load("gv", "snakes.nets", "nets")

### ISSUE THREAD

**Issue by fkgl** [fpom/snakes#18]
Hi,
please, I'm using python 3.8 with Pycharm IDE 2020.1.1 , I'm trying to use snakes but I can't load plugins (snakes.plugins.load("gv", "snakes.nets", "nets")
from nets import *)
if I pass the mouse on the load the message (You need configured Python 2 SDK to render Epydoc docstrings) is displayed.
I don't know if that is the problem or there is another problem
I try to install epydoc but the problem is not resolved;
please can someone help me?

**Comment by fpom** [comment]
SNAKES is not completely well ported to Python 3, does it work with Python 2.7?

**Comment by fkgl** [comment]
@fpom 
ok, I will try Python2.7
Thank you.
