### ISSUE TITLE
Drawing a petrinet not possible/add documentation for graphviz

### ISSUE THREAD

**Issue by LinqLover** [fpom/snakes#21]
The docs says there would be a method `PetriNet.draw`, but there is no such method in this repository. Also, it mentions a plugin `graphviz` that is nowadays called `gv`. How can I draw a petrinet?

**Comment by m-h-b-tu** [comment]
The method is added to `PetriNet` by the plugin `gv`. You need to load it. Just follow the examples from the [docs](https://snakes.ibisc.univ-evry.fr/API/plugins/gv.html).

**Comment by fpom** [comment]
Yes, indeed. Thank you for answering!
Franck
