### ISSUE TITLE
Error 404 with project link to the documentation

### ISSUE THREAD

**Issue by ljaniec** [fpom/snakes#24]
Hello,
I got error 404 after clicking the link to the homepage:

> This user is unkown or this page is not found !
> 
> Try to find him in this page!
> 
> — Tech-staff
> Cette personne n'est pas connue ou cette page est introuvable !
> 
> Essayez de le trouver dans cette page
> 
> — Tech-staff

Could you update the link or get the same site up again?

Best regards
ljaniec

**Comment by fpom** [comment]
SNAKES doc is now here: https://snakes.ibisc.univ-evry.fr
Could you tell me where in the doc you've had an invalid address?

**Comment by ljaniec** [comment]
Hi,
I used a link to documentation from there:
https://pypi.org/project/SNAKES/0.9.17/

Thank you for the link and the proper source.

**Comment by fpom** [comment]
Oh yes, thank you. I've fixed with a new version.
