### ISSUE TITLE
imp library obsolete, to be replaced by importlib

### ISSUE THREAD

**Issue by g-gg** [fpom/snakes#32]
Dear Mr Pommereau and all other contributors,
thank you for creating and maintaining this library. I stumbled across fundamental problems with python 3.12:

`import snakes.plugins` fails with
> Exception has occurred: ModuleNotFoundError
> No module named 'imp'

Indeed the imp library has been marked as obsolete. Quoting from the [python 3.10 documentation on the imp library](https://docs.python.org/3.10/library/imp.html):
Deprecated since version 3.4: The [imp](https://docs.python.org/3.10/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3.10/library/importlib.html#module-importlib).

It seems to me that for the call `imp.new_module` in the function build() in plugins/__init__.py there is no direct equivalent in the importlib function, so this could be a starting point. Disclaimer: I've never used neither of the libraries.

Thank you

**Comment by fpom** [comment]
Hi, Thank you for your report. This should be fixed in the latest commit.
Franck

**Comment by g-gg** [comment]
thank you for resolving this so promptly, I confirm that the issue is solved now with the latest commit.
