### ISSUE TITLE
Check for empty Places in Expression

### ISSUE THREAD

**Issue by chris-kuhr** [fpom/snakes#8]
Hi,

I am developing a Gui simulator based on SNAKES.

I have a transition with two inputs and one output.
The output shall only forward a token, if one input place is empty.
The problem is, that the transition is not enabled for this situation. No mode for an empty place.

I tried working around in the code, by removing the input with the empty place, based on the is_empty() function call, and substitute the expression ( remove_output, add_output ) on the output arc. but this is ugly and does not work so far.

Is it possible to check for an empty place in an expression, or do I really have to work around this?
I tried: 
"x if y==[] else None"
"x if y==MultiSet([]) else None"

I could not attach a screenshot, something "went really wrong"... could send it via email though...

**Comment by fpom** [comment]
> I am developing a Gui simulator based on SNAKES.

Good news, let me know how it progress!

> The problem is, that the transition is not enabled for this situation. No mode for an empty place.

This is the expected behaviour of a standard Petri net.

> I have a transition with two inputs and one output.
> The output shall only forward a token, if one input place is empty.

From your code snippet, I understand the following:
- three places, call them `a`, `b`, `c`
- one transition `t`
- one arc `a->t` labelled by `x`
- one arc `b->t` labelled by `y`
- one arc `t->c` labelled by `x`
- you want `t` to fire only if `b` is empty

If this is your setting, you need an inhibitor arc, this is a classical Petri net extension and SNAKES implements it with class `Inhibitor`. All what you need is to insert is as `net.add_input("b", "t", Inhibitor(Variable("y")))`.

Have a look at the doc for further info: https://www.ibisc.univ-evry.fr/~fpommereau/SNAKES/API/nets.html#hdr-726677f7e3be0abb

Does this solve your issue?

Cheers,
Franck

**Comment by chris-kuhr** [comment]
Hi,

thanks for answer.

I implemented only general Places without type checking. Everything is a string, because this makes IP packet dissection possible.  :-)
The simulator has the possibility for hierarchical subnets, which took a lot of time and nerves... but finally it is working.
I hadn't found your .pnml  files until recently, thus I have my own XML format, but that should be made compatible easily.
You can also export each step as SVG file.

First I want to create some more complex nets, then I will upload it to github.
I will write a brief manual, so that you could try it. I would really like to know your opinion about it.
A complete documentation will be part of my master thesis. As soon as it is ready, I will let you know.

But now to the Inhibitor Arc.
I gave it a try. For an arc annotation of `y==[]`  an inhibitor arc is added to the net with `Variable("y")`. 
In the situation, when `b` is empty and a token is present in `a`, I have a `DomainError Exception: Token unbound variable "y"` . The token from `a` should be forwarded to `c` instead.
I am not quite clear about the meaning, could you enlighten me?

BR,
Chris

**Comment by fpom** [comment]
There where a bug indeed, I've pushed an update onto the repository. Inhibitor arcs are not frequently used and so have not been tested enough, I'm happy you use them so I'll be more confident if they work for you.

I could run correctly this code:

```
from snakes.nets import *
n = PetriNet("n")
n.add_place(Place("a", ["hello"]))
n.add_place(Place("b", []))
n.add_place(Place("c", []))
n.add_transition(Transition("t"))
n.add_input("a", "t", Variable("x"))
n.add_input("b", "t", Inhibitor(Variable("y")))
n.add_output("c", "t", Variable("x"))
t = n.transition("t")
m = t.modes()[0]
t.fire(m)
assert n.get_marking() == Marking({"c" : MultiSet(["hello"])})
```

So hopefully this should be OK now.

**Comment by chris-kuhr** [comment]
That's it!

Now it is working. 
I have a relativly complex working example.
Tomorrow I will comment the code, write a brief manual and upload it to github (including the example).

Thanks!

BR,
Chris

**Comment by fpom** [comment]
Good, looking forward to seeing your code. 
Franck
