### ISSUE TITLE
CPN Simulator Gui

### ISSUE THREAD

**Issue by chris-kuhr** [fpom/snakes#9]
Hi,
I didn't know where else to post this.
I created a repository for the CPN Simulator Gui:
https://github.com/chris-kuhr/CPNSimulatorGui
The `setup.py` does not work yet.
The complete sphinx documentation is in subfolder `docs`

I would be glad to hear some opinions. 
Working examples are in the folder: `src/output/cpn`.
 I was not able to write a manual yet, this will follow in the next days.
In ultra brief:
- Drag Icons from top-left onto drawing area.
- Hold Shift key and left click connector box at source, hold shift-key and left mouse button, move to destination item and release mouse button over connector box.
- A color must be defined, then drag a Token Item from top-left onto place.

BR,
Chris

**Comment by himito** [comment]
Hi!,

thank you for your tool. It will be very useful for some ideas that I have in mind.

Jaime.

**Comment by fpom** [comment]
I've created a page to list tools that use SNAKES:
https://www.ibisc.univ-evry.fr/~fpommereau/SNAKES/related-tools.html

I was unable to test yet: my default Python is still 2.7, so it does not work out of the box. I have to take the time to setup a virtualenv with all the requirements.

If you want a more detailed description, please send me something.

Franck
